name:                webby
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/webby#readme
license:             BSD3
author:              Aditya Manthramurthy
maintainer:          aditya@minio.io
copyright:           2018 Aditya Manthramurthy
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - binary
  - bytestring
  - http-types
  - mtl
  - protolude
  - resourcet
  - text
  - unliftio
  - wai
  - wai-extra
  - warp

source-dirs:
  - src

library:
  exposed-modules:
    - Webby

executables:
  webby-example:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - conduit
      - webby

default-extensions:
  - FlexibleInstances
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections
